[phases.setup]
nixPkgs = ['python313', 'pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'python manage.py migrate && gunicorn portfolio.wsgi:application --bind 0.0.0.0:$PORT'
